# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.6
    environment:
      DBT_URL:                 https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:           'Circle CI PR Job' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:          66543
      DBT_PROJECT_ID:          152723
      DBT_PR_JOB_ID:           123539
      DBT_JOB_SCHEMA_OVERRIDE: ${{github.event.pull_request.number}}
      DBT_JOB_BRANCH:          ${{github.head_ref}} 
    steps:
      - checkout
      - run: python --version
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: |
          python -u ./python/run_and_monitor_dbt_cloud_job.py